name: 'setup-dlang test action'
description: 'Verify a D compiler installation'
inputs:
  dc:
    description: 'D compiler passed to setup-dlang'
    required: false
    default: ''
  gh_token:
    description: "Token to use when doing Github API request (for ldc-master)"
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Install D compiler
      uses: ./
      with:
        compiler: ${{ inputs.dc }}
        gh_token: ${{ inputs.gh_token }}

    - name: Verify D compiler ($DC)
      shell: bash
      run: $DC .github/hello.d && ./hello

    - name: Verify D compiler with explicit bitness ($DC)
      if: ${{ startsWith(inputs.dc, 'dmd') }}
      shell: bash
      run: $DC -m64 .github/hello.d && ./hello

    - name: Verify D compiler ($DC, shared)
      if: ${{ !startsWith(inputs.dc, 'g') }} # fails with gdc
      shell: bash
      run: $DC -shared .github/hello.d && ./hello

    - name: Verify D compiler (dub)
      if: ${{ !startsWith(inputs.dc, 'g') }} # dub doesn't come with gdc by default
      shell: bash
      run: dub run --single -q .github/hello.d

    - name: Install Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Ensure `dist/index.js` is up to date
      env:
          NODE_OPTIONS: "--openssl-legacy-provider"
      run: |
        set -euxo pipefail
        npm ci
        npm run build
        # exclude dist/index.js.map (different on Windows)
        git diff --stat --exit-code HEAD -- ':!dist/index.js.map'
      shell: bash
