name: 'setup-dlang test action'
description: 'Verify a D compiler installation'
inputs:
  dc:
    description: 'D compiler passed to setup-dlang'
    required: false
    default: ''
  gh_token:
    description: "Token to use when doing Github API request (for ldc-master)"
    default: ${{ github.token }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Install D compiler
      uses: ./
      with:
        compiler: ${{ inputs.dc }}
        gh_token: ${{ inputs.gh_token }}

    - name: Verify D compiler ($DC)
      shell: bash
      run: $DC .github/hello.d && ./hello

    - name: Verify D compiler with explicit bitness ($DC)
      if: ${{ startsWith(inputs.dc, 'dmd') }}
      shell: bash
      run: $DC -m64 .github/hello.d && ./hello

    - name: Verify D compiler ($DC, shared)
      if: ${{ !startsWith(inputs.dc, 'g') }} # fails with gdc
      shell: bash
      run: $DC -shared .github/hello.d && ./hello

    - name: Verify D compiler (dub)
      if: ${{ !startsWith(inputs.dc, 'g') }} # dub doesn't come with gdc by default
      shell: bash
      run: dub run --single -q .github/hello.d
