name: Run the typescript unittests
on:
  push:
    branches:
    - "v*"
  pull_request:
    branches:
    - "*"
defaults:
  run:
    shell: bash

jobs:
  run-typescript-unittests:
    name: Run all the typescript unittests
    strategy:
      fail-fast: false
      matrix:
        # This could be run on only one machine but run on all of them
        # to make sure that other developers can run the tests on
        # their system.
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run `npm test`
        run: |
          set -euxo pipefail
          npm ci
          GITHUB_ENV= GITHUB_PATH= npm test
